name: AutoCheckIn

on:
  workflow_dispatch:
  watch:
    types: [started]
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 'Install requirements'
        run: |
          python -m pip install --upgrade pip
          pip install -r .\requirements.txt

      - name: 'Setup ChromeDriver'
        uses: nanasess/setup-chromedriver@v1
        # with:
        #   # Optional: do not specify to match Chrome's version
        #   chromedriver-version: '88.0.4324.96'
        
      # - name: Get Chrome version
      #   id: get_chrome_version
      #   run: |
      #     $chromeVersion = (Get-ItemProperty "HKCU:\Software\Google\Chrome\BLBeacon").version

      - name: 'Envoriment'
        env:
          cookies: ${{ secrets.COOKIES }}
          account: ${{ secrets.ACCOUNT }}
          password: ${{ secrets.PASSWORD }}
        run: |
          python .\SteamzgAutoCheckIn.py
