name: AutoCheckIn

on:
  workflow_dispatch:
  watch:
    types: [started]
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 'Install requirements'
        run: |
          python -m pip install --upgrade pip
          pip install -r .\requirements.txt

      - name: 'Envoriment'
        env:
          cookies: ${{ secrets.COOKIES }}
        run: |
          cd $GITHUB_WORKSPACE
          python .\SteamzgAutoCheckIn.py
